// ES - 50 maker/designer quotes
// Generated for PanHandler i18n

export const quotes_es: string[] = [
  "Measure twice, cut once.",
  "Precision is the difference between amateur and professional.",
  "Good design is invisible.",
  "Form follows function.",
  "Simplicity is the ultimate sophistication.",
  "The best designs are the ones you don't notice.",
  "Engineering is the art of organizing technology.",
  "A good craftsman never blames their tools.",
  "Prototype early, prototype often.",
  "Iteration is the key to perfection.",
  "Constraints breed creativity.",
  "Design is not just what it looks like, it's how it works.",
  "The details are not the details. They make the design.",
  "Less is more.",
  "If you can't explain it simply, you don't understand it well enough.",
  "If you can dream it, you can build it.",
  "The best time to start was yesterday. The second best time is now.",
  "Build something that matters.",
  "Every expert was once a beginner.",
  "Fail fast, learn faster.",
  "Your first version doesn't have to be perfect.",
  "Done is better than perfect.",
  "The only way to do great work is to love what you do.",
  "Make something people want.",
  "Creativity is intelligence having fun.",
  "Innovation distinguishes between a leader and a follower.",
  "Ideas are cheap. Execution is everything.",
  "The best way to predict the future is to create it.",
  "Build, measure, learn.",
  "Start where you are. Use what you have. Do what you can.",
  "Dream big, start small.",
  "Progress, not perfection.",
  "Every master was once a disaster.",
  "Believe in yourself and all that you are.",
  "Small steps every day.",
  "You are capable of amazing things.",
  "Create the future you want to see.",
  "Don't wait for opportunity. Create it.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "The journey of a thousand miles begins with a single step.",
  "I void warranties.",
  "Duct tape fixes everything. Except relationships.",
  "Coffee: Because adulting is hard.",
  "I'm not procrastinating, I'm prototyping.",
  "This is a feature, not a bug.",
  "Works on my machine.",
  "It's not broken, it's just... redesigned.",
  "I didn't choose the maker life. The maker life chose me.",
  "My other project is also unfinished.",
  "Powered by caffeine and stubbornness.",
];
